### ISSUE TITLE
async/await in IE 11 doesn't work

### ISSUE THREAD

**Issue by sailo89** [aurelia/polyfills#16] opened 2016-03-21 14:51 UTC
When running my app in IE, it sticks at loading the app with the following error:

INFO [aurelia] Aurelia Started
Potentially unhandled rejection [1] TypeError: Object.getOwnPropertyNames: argument is not an Object
   at createWithSymbols (eval code:50:7)
   at descriptor.value (eval code:169:7)
   at create (eval code:4:3)
   at wrap (eval code:25:7)
   at runtime.async (eval code:122:7)
   at activate (eval code:85:25)
   at tryActivateViewModel (eval code:3891:5)
   at $ (http://localhost:9000/jspm_packages/system-polyfills.js:4:8727)
   at H (http://localhost:9000/jspm_packages/system-polyfills.js:4:8314)
   at R.prototype.when (http://localhost:9000/jspm_packages/system-polyfills.js:4:12046)

I've discussed this issue with Souldrinken, and he gave me the advice to import core-js before importing aurelia-bootstrapper, like:

`System.import('core-js').then(function () {
       return System.import('aurelia-bootstrapper');
 });`

**Comment by EisenbergEffect** [comment] 2016-03-21 15:07
Can you provide a repro for this? Also...I would need some more information about how async/await relates to this. That feature may rely on additional polyfills, for example.,

**Comment by EisenbergEffect** [comment] 2016-03-21 16:36
This may already be fixed. We'll have some updates tomorrow.

**Comment by sailo89** [comment] 2016-03-22 08:59
I'll check today if the updates help solve this problem.
With repro do you mean a plunker example?

I can show you the code where it all happens:

`async activate() {
        if(!sessionStorage.getItem('patientsJSON')) {
            await this.http.get(this.config.get('api_url') + "Patients").then(response => {
                sessionStorage.setItem('patientsJSON', JSON.stringify(response.content));
            });
        }
        if(!localStorage.getItem('nomenclaturesJSON')) {
            await this.http.get(this.config.get('api_url') + "Nomenclatures").then(response => {
                localStorage.setItem('nomenclaturesJSON', JSON.stringify(response.content));
            });
        }
        if(!localStorage.getItem('citiesJSON')) {
            this.http.get(this.config.get('url') + "data/cities.json").then(response => {
                localStorage.setItem('citiesJSON', JSON.stringify(response.content));
            });
        }
    }`

I have this in my app.js. Everything runs fine in IE when adding the following lines in index.html:

`System.import('core-js').then(function () { return System.import('aurelia-bootstrapper'); });`
 
But I have also some problems bundling the app, it keeps looking for core-js. Even if I add it to the bundles.

I think the main issue here is something with polyfills? I hope this get solved so I don't have to import core-js.

**Comment by EisenbergEffect** [comment] 2016-03-22 10:46
It's the code I need, but a reproduction. I have to be able to reproduce it in the skeleton app or else we can't figure out how to fix it.

**Comment by sailo89** [comment] 2016-03-22 13:27
I've created a repro, how can I share this with you?

**Comment by EisenbergEffect** [comment] 2016-03-22 13:40
If you can just attach it to this issue that would be fine.

**Comment by sailo89** [comment] 2016-03-22 15:19
[ie_bug.zip](https://github.com/aurelia/polyfills/files/184379/ie_bug.zip)

**Comment by sailo89** [comment] 2016-03-24 07:23
Hi Rob, did you get the chance to solve this issue?

**Comment by EisenbergEffect** [comment] 2016-03-24 10:43
@jdanyow Do you have time to look at this IE issue? There's a repro linked above.

**Comment by jdanyow** [comment] 2016-03-24 21:14
@sailo89 this is the current status right?

>I have this in my app.js. Everything runs fine in IE when adding the following lines in index.html:
System.import('core-js').then(function () { return System.import('aurelia-bootstrapper'); });
But I have also some problems bundling the app, it keeps looking for core-js. Even if I add it to the bundles.
I think the main issue here is something with polyfills? I hope this get solved so I don't have to import core-js.

If so, please close this issue, and open a new issue in the [bundler repo](https://github.com/aurelia/bundler) with the new error details.  I'm guessing the problem is something to do with not bundling the babel runtime.

**Comment by TGMorais** [comment] 2016-03-27 17:03
Hi, I was about to open an issue when i saw this one..
I'm having the same/similar problem.

I'm using the [webpack skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016-webpack).

I added the webpack plugins to transform so they could compile to module ( I also tried the other plugin to [asyn-to-generator](http://babeljs.io/docs/plugins/transform-async-to-generator) )

`webpack.config.js`

```javascript
{ test: /\.js$/, loader: 'babel', exclude: /node_modules/, query: { presets: ['es2015-loose', 'stage-1'],  plugins: 
        [
            ["transform-async-to-module-method", {
              "module": "bluebird",
              "method": "coroutine"
            }],    
            'transform-runtime',
            'transform-decorators-legacy'
          ] } 
      },
```


Then I simply added a small exapmle to the `welcome.js`  `submit()`
```javascript
 submit() {
    
    ///"BREAKS ON IE""
    async function sleep(ms = 0) {
      return new Promise(r => setTimeout(r, ms));
    }
    
    async function conversation () {
      console.log("llalal")
      let hi = await sleep(1000)
      console.log(hi);
    }
    conversation();
    //END OF "BREAKS ON IE"
    
    this.previousValue = this.fullName;
    alert(`Welcome, ${this.fullName}!`);
  }
```

On IE11 I always get the same exception, being thrown in `aurelia-polyfills.js`
I don't have to actually call any async function, the exception is thrown just be having the function defined.

Which leads me to believe its not actually async wait problems but some bug in aurelia's polyfllls.

I really would rather not import core-js just for this :(

I setup the project [here](https://github.com/TGMorais/aurelia-skeleton-2016-webpack-async) with the problem

**Comment by TGMorais** [comment] 2016-03-31 14:50
@jdanyow Any way I can get a hand about this :) ?

**Comment by Leonidnei** [comment] 2016-04-04 13:13
We also have this problem: after upgrading to the latest Aurelia version and switching to Babel 6 we got "Object.getOwnPropertyNames: argument is not an Object" in IE 11 (it worked in Chrome).

Adding:
System.import('core-js').then(function () { return System.import('aurelia-bootstrapper'); });
bypassed the problem, but we are looking for perm solution.

We use async/await in our code.

**Comment by EisenbergEffect** [comment] 2016-04-04 13:16
If you can help us track down the issue, we can get a patch out asap.

**Comment by Leonidnei** [comment] 2016-04-04 13:17
How we can help with this?

**Comment by EisenbergEffect** [comment] 2016-04-04 13:20
If you can track down which polyfill is causing the problem and identify a fix that would help. If you are able to submit a PR, we can even get the release out the same day as the PR is submitted probably.

**Comment by jdanyow** [comment] 2016-04-11 03:28
I wasn't able to reproduce this.  If someone wants to fork one of the skellys and put together a repro that we can `npm install;jspm install;gulp watch` it would speed things up.

**Comment by EisenbergEffect** [comment] 2016-07-04 22:09
Looks like this issue has been resolved through various fixes.

**Closed by EisenbergEffect** 2016-07-04 22:09 UTC
