### ISSUE TITLE
IE11 - TypeError

### ISSUE THREAD

**Issue by akaustav** [aurelia/polyfills#11] opened 2016-03-07 20:36 UTC
Today, I upgraded from `aurelia-polyfills v1.0.0-beta.1.0.0` to `aurelia-polyfills v1.0.0-beta.1.0.2` using a `jspm update` and I received the following error message on the console on **Microsoft Internet Explorer 11**:

> Potentially unhandled rejection [1] TypeError: Object.keys: argument is not an Object
>    at assign (Unknown script code:446:13)
>    at activate (Unknown script code:1513:7)
>    at Anonymous function (Unknown script code:1485:23)
>    at M (http://localhost:9000/jspm_packages/system-polyfills.js:4:8723)
>    at H (http://localhost:9000/jspm_packages/system-polyfills.js:4:8310)
>    at R.prototype.when (http://localhost:9000/jspm_packages/system-polyfills.js:4:12042)
>    at b.prototype.run (http://localhost:9000/jspm_packages/system-polyfills.js:4:11076)
>    at t.prototype._drain (http://localhost:9000/jspm_packages/system-polyfills.js:4:3014)
>    at drain (http://localhost:9000/jspm_packages/system-polyfills.js:4:2681)
>    at e (http://localhost:9000/jspm_packages/system-polyfills.js:4:4595)

Is anyone else getting this error?

**Comment by EisenbergEffect** [comment] 2016-03-07 20:42
We have identified the error. Fix is coming today.

**Comment by EisenbergEffect** [comment] 2016-03-07 20:42
See here for an explanation: https://github.com/aurelia/polyfills/issues/8

**Comment by akaustav** [comment] 2016-03-07 21:22
Thanks. Will wait for the fix.

**Comment by EisenbergEffect** [comment] 2016-03-07 21:47
Closing as duplicate of #8

**Closed by EisenbergEffect** 2016-03-07 21:47 UTC
